services:
  db:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ordersdb
      MYSQL_USER: ordersapp
      MYSQL_PASSWORD: orderspass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080" # Access Adminer on http://localhost:8888
    depends_on:
      - db

  meilisearch:
    image: getmeili/meilisearch:v1.12
    restart: always
    volumes:
      - ./data.ms:/data.ms # Persists Meilisearch data
    ports:
      - "7700:7700"

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379
      ALLOW_EMPTY_PASSWORD: "yes" # For dev only! Secure in prod.

  app:
    build: working
    image: order-service:latest          # produced by Jib
    depends_on:
      - db
      - redis
      - meilisearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/ordersdb
      SPRING_DATASOURCE_USERNAME: ordersapp
      SPRING_DATASOURCE_PASSWORD: orderspass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_API_KEY:
    ports:
      - "8080:8080"

volumes:
  db_data: